/* Generated By:JavaCC: Do not edit this line. MyNewGrammarConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyNewGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Plus = 5;
  /** RegularExpression Id. */
  int Number = 6;
  /** RegularExpression Id. */
  int Assignment = 7;
  /** RegularExpression Id. */
  int Semicolon = 8;
  /** RegularExpression Id. */
  int If = 9;
  /** RegularExpression Id. */
  int Else = 10;
  /** RegularExpression Id. */
  int LeftParenthesis = 11;
  /** RegularExpression Id. */
  int RightParenthesis = 12;
  /** RegularExpression Id. */
  int LeftBrace = 13;
  /** RegularExpression Id. */
  int RightBrace = 14;
  /** RegularExpression Id. */
  int InputEnd = 15;
  /** RegularExpression Id. */
  int Compare = 16;
  /** RegularExpression Id. */
  int Id = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "<Number>",
    "\":=\"",
    "\";\"",
    "\"if\"",
    "\"else\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"end\"",
    "<Compare>",
    "<Id>",
  };

}
