/* Generated By:JavaCC: Do not edit this line. MyNewGrammarConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyNewGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Plus = 5;
  /** RegularExpression Id. */
  int Number = 6;
  /** RegularExpression Id. */
  int Assignment = 7;
  /** RegularExpression Id. */
  int Semicolon = 8;
  /** RegularExpression Id. */
  int InputEnd = 9;
  /** RegularExpression Id. */
  int Id = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "<Number>",
    "\":=\"",
    "\";\"",
    "\"end\"",
    "<Id>",
  };

}
