/* Generated By:JavaCC: Do not edit this line. MyNewGrammarConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyNewGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MULTIPLY = 6;
  /** RegularExpression Id. */
  int Type = 7;
  /** RegularExpression Id. */
  int DOUBLE = 8;
  /** RegularExpression Id. */
  int Bool = 9;
  /** RegularExpression Id. */
  int Id = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<PLUS>",
    "<MULTIPLY>",
    "<Type>",
    "<DOUBLE>",
    "<Bool>",
    "<Id>",
    "\" = \"",
    "\";\"",
  };

}
